apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: blue-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-app
  template:
    metadata:
      labels:
        app: blue-app
    spec:
      containers:
        - name: devops-capstone
          image: prhomhyse/devops-capstone:latest
          ports:
            - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: webapp-service
spec:
  selector:
    app: blue-app
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-02-10T00:01:07Z"
  name: jenkins
  namespace: default
  resourceVersion: "38603"
  selfLink: /api/v1/namespaces/default/serviceaccounts/jenkins
  uid: 700c6108-4b98-11ea-8719-026b4938109a
secrets:
  - name: jenkins-token-6zgcr
---

